name: payments_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  bloc: ^9.1.0
  dio: ^5.9.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_credit_card: ^4.1.0
  flutter_dotenv: ^6.0.0
  flutter_stripe: ^12.1.0
  font_awesome_flutter: ^10.12.0
  gap: ^3.0.1
  go_router: ^17.0.0
  meta: ^1.16.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - .env